const NavigatorConsts = {
  EventName: 'Event Name',
  EventStartDate: 'Event Start Date',
  EventEndDate: 'Event End Date',
  NewOrExisting: 'New or Existing',
  EventType: 'Event Type',
  EstRevenue: 'Est. Revenue',
  NoOfAttendees: '# of Attendees',
  EndUserAccount: 'End User Account',
  EndUserContact: 'End User Contact',
  Venue: 'Venue',
  ShowCategory: 'Show Category',
  GLCenter: 'GL Center',
  greenIconText: 'text-green-500',
  yellowIconText: 'text-yellow-500',
  redIconText: 'text-red-500',
  moodIconText: 'text-gray-500',
  happyLogMsg: 'Happy Room Mood',
  neutralLogMsg: 'Neutral Room Mood',
  angryLogMsg: 'Dissatisfied Room Mood',
  Equipment: 'Equipment',
  Notes: 'Notes',
  Log: 'Log',
  Contacts: 'Contacts',
  Add_Ons: 'Add Ons',
  Labor: 'Labor',
  tabNames: ['Details', 'Contacts', 'Touchpoints', 'Room List', 'Previous Events'],
  Languages: ['English', 'Spanish', 'French'],
  blackColor: 'rgb(0, 0, 0)',
  scheduleColor: 'rgb(55, 65, 81)',
  flowsheetDarkColor: 'rgb(229, 231, 235)',
  scheduleDarkColor: 'rgb(209, 213, 219)',
  customersColor: 'rgb(209, 213, 219)',
  menuBgDarkColor: 'rgb(12, 74, 110)',
  menuBgLightColor: 'rgb(56, 189, 248)',
  favouriteIconColor: 'text-purple-500',
  menuSlotsText: ['Logs', 'Location Profile', 'Customers'],
  startDate : "Start Date",
  endDate : "End Date",
  eventName : "Event Name",
  moodChangeMessage:"Happy Room Mood",
  statusRefreshCompleteMsg:"Set - Refresh Complete Status Change"
};

exports.Const = NavigatorConsts;
