const NavigatorConsts = {
  EventName: 'Event Name',
  EventStartDate: 'Event Start Date',
  EventEndDate: 'Event End Date',
  NewOrExisting: 'New or Existing',
  EventType: 'Event Type',
  EstRevenue: 'Est. Revenue',
  NoOfAttendees: '# of Attendees',
  EndUserAccount: 'End User Account',
  EndUserContact: 'End User Contact',
  Venue: 'Venue',
  ShowCategory: 'Show Category',
  GLCenter: 'GL Center',
  greenIconText: 'text-green-500',
  yellowIconText: 'text-yellow-500',
  redIconText: 'text-red-500',
  moodIconText: 'text-gray-500',
  happyLogMsg: 'Happy Room Mood',
  neutralLogMsg: 'Neutral Room Mood',
  angryLogMsg: 'Dissatisfied Room Mood',
  Equipment: 'Equipment',
  Notes: 'Notes',
  Log: 'Log',
  Contacts: 'Contacts',
  Add_Ons: 'Add Ons',
  Labor: 'Labor',
  tabNames: ['Details', 'Contacts', 'Touchpoints', 'Room List', 'Previous Events'],
  Languages: ['English', 'Spanish', 'French']
};

exports.Const = NavigatorConsts;
